apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

namespace: prod

images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.2"

patches:
  - path: minimum-replicas.yaml
    target:
      kind: Deployment
